### ISSUE TITLE
Testing output is spammy

### ISSUE THREAD

**Issue by berquist** [cclib/Cclib.jl#14]
Calling
```
(Cclib) pkg> test
```
in the REPL runs mamba every time for some reason, and it is not quiet.  The progress bars show and don't update in place, so the terminal quickly fills with tens of thousands of lines.

**Comment by vcanogil** [comment]
I've noticed that too, although it's not every time for me. Just once in a while it would go through the entire process of setting everything up. 

We'll be taking a look into at a later stage of the project

**Comment by vcanogil** [comment]
Is this still an issue? It seems to be behaving normally for me now.

**Comment by berquist** [comment]
It's pretty much always reinstalling from scratch for me, but the output isn't messed up anymore.
