### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by berquist** [cclib/Cclib.jl#4]
Should we add 0.1.0 to the registry as-is, before any further development?

**Comment by berquist** [comment]
We agreed some time ago to not do so, but now we are ready to make a release.  Probably pushing a tag will do it automatically?

**Comment by vcanogil** [comment]
We can use a [register bot ](https://github.com/JuliaComputing/Registrator.jl?setup_action=request#how-to-use) to register and release versions. I made a request for it to have access, you should receive it (hopefully) soon.

**Comment by berquist** [comment]
Ok, I added it.

**Comment by vcanogil** [comment]
[Version was updated](https://github.com/cclib/Cclib.jl/pull/15), so registering the package. 
@JuliaRegistrator register()

**Comment by berquist** [comment]
Done in https://github.com/JuliaRegistries/General/pull/88006 :tada:
